FROM nginx:1.21-alpine AS base

WORKDIR /web

FROM base AS dev

FROM base AS prod

# Set permissions for 'nginx' user
# COPY --chown=nginx:nginx --chmod=640  /web /web
COPY ./web /web
RUN set -eux; \
    chown -R nginx:nginx /web; \
    find /web -type d -exec chmod 750 {} \; ; \
    find /web -type f -exec chmod 640 {} \; ;

# Add default configs
COPY config/web/nginx/nginx.conf /etc/nginx/nginx.conf
