FROM nginx:1.21-alpine AS base

WORKDIR /web

FROM base AS dev

FROM base AS prod-base

# Set permissions for 'nginx' user
COPY ./web /web
RUN chown -R nginx:nginx . \
    && find . -type d -exec chmod 750 {} \; \
    && find . -type f -exec chmod 640 {} \;

FROM base AS prod

# COPY --from=prod-base /web /web
COPY --chown=nginx:nginx --chmod=640  /web /web

# Add default configs
COPY config/web/nginx/nginx.conf /etc/nginx/nginx.conf
